# Generated by Django 6.0.4 on 2026-04-24 10:28

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bank_app', '0005_alter_account_public_id_alter_card_public_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TransactionInside',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('type', models.CharField(choices=[('phone_num', 'Phone Number'), ('card', 'Card')], max_length=20)),
                ('sender', models.CharField(max_length=20)),
                ('reciver', models.CharField(max_length=20)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('cuur_balance_sender', models.DecimalField(decimal_places=2, max_digits=12)),
                ('cuur_balance_reciver', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.CharField(blank=True, max_length=255)),
                ('status', models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=10)),
            ],
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='account2',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='current_balance_account1',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='current_balance_account2',
        ),
        migrations.AddField(
            model_name='card',
            name='cart_name',
            field=models.CharField(choices=[('visa', 'Visa'), ('credit', 'Credit'), ('master', 'Master'), ('simple', 'Simple')], default='simple', max_length=10),
        ),
        migrations.AddField(
            model_name='card',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='card',
            name='cvv',
            field=models.CharField(default='000', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='card',
            name='expair',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='credit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('failed', 'Failed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='deposit',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('closed', 'Closed'), ('failed', 'Failed')], default='active', max_length=10),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cuur_balance_reciver',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='cuur_balance_sender',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='transaction',
            name='reciver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_transactions', to='bank_app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='sender',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_transactions', to='bank_app.account'),
        ),
        migrations.AddField(
            model_name='transaction',
            name='status',
            field=models.CharField(choices=[('success', 'Success'), ('failed', 'Failed'), ('pending', 'Pending')], default='success', max_length=10),
        ),
        migrations.AlterField(
            model_name='account',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='card',
            name='card_number',
            field=models.CharField(max_length=16, unique=True, validators=[django.core.validators.RegexValidator('^\\d{16}$', 'Card number must contain exactly 16 digits.')]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='credit',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='deposit',
            name='percent',
            field=models.DecimalField(decimal_places=2, max_digits=5, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=12, validators=[django.core.validators.MinValueValidator(0.01)]),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='description',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('phone_num', 'Phone Number'), ('card', 'Card')], max_length=20),
        ),
        migrations.CreateModel(
            name='AccountBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='bank_app.account')),
            ],
        ),
        migrations.CreateModel(
            name='CardBlackList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('description', models.CharField(max_length=255)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blacklist_entries', to='bank_app.card')),
            ],
        ),
    ]
